# Exploring Embedding Models in LangChain

## Install OpenAI, HuggingFace and LangChain dependencies

In [1]:
!pip install langchain==0.3.11
!pip install langchain-openai==0.2.12
!pip install langchain-community==0.3.11
!pip install langchain-huggingface==0.1.2

## Enter Open AI and HuggingFace API Tokens

In [2]:
from getpass import getpass

OPENAI_KEY = getpass('Enter Open AI API Key: ')

In [3]:
from getpass import getpass

HUGGINGFACEHUB_API_TOKEN = getpass('Enter HuggingFace Auth Token Key: ')

## Setup Environment Variables

In [4]:
import os

os.environ['OPENAI_API_KEY'] = OPENAI_KEY
os.environ['HUGGINGFACEHUB_API_TOKEN'] = HUGGINGFACEHUB_API_TOKEN

## Embedding models

The Embeddings class is a class designed for interfacing with text embedding models. There are lots of embedding model providers (OpenAI, Cohere, Hugging Face, etc) - this class is designed to provide a standard interface for all of them.

Embeddings create a vector representation of a piece of text. This is useful because it means we can think about text in the vector space, and do things like semantic search where we look for pieces of text that are most similar in the vector space.

The base Embeddings class in LangChain provides two methods: one for embedding documents and one for embedding a query. The former takes as input multiple texts, while the latter takes a single text. The reason for having these as two separate methods is that some embedding providers have different embedding methods for documents (to be searched over) vs queries (the search query itself).

In [5]:
docs = [
    "cats eat and sleep",
    "dogs eat and bark",
    "cars drive fast",
    "vehicles include trucks and cars"
]

Embeddings create a vector representation of a piece of text. This is useful because it means we can think about text in the vector space, and do things like semantic search where we look for pieces of text that are most similar in the vector space.

The base Embeddings class in LangChain provides two methods: one for embedding documents and one for embedding a query. The former, `.embed_documents`, takes as input multiple texts, while the latter, `.embed_query`, takes a single text. The reason for having these as two separate methods is that some embedding providers have different embedding methods for documents (to be searched over) vs queries (the search query itself).

- `.embed_query`  will return a list of floats,
- `.embed_documents` returns a list of lists of floats.

### Open AI Embedding Models

LangChain enables us to access Open AI embedding models which include the newest models: a smaller and highly efficient `text-embedding-3-small` model, and a larger and more powerful `text-embedding-3-large` model.

In [6]:
from langchain_openai import OpenAIEmbeddings

# details here: https://openai.com/blog/new-embedding-models-and-api-updates
openai_embed_model = OpenAIEmbeddings(model='text-embedding-3-small')

In [7]:
embeddings = openai_embed_model.embed_documents(docs)

In [8]:
len(embeddings)

4

In [12]:
print(embeddings)

[[-0.01413703616708517, -0.004930549301207066, -0.009022679179906845, 0.011621778830885887, 0.020238148048520088, 0.026752019301056862, 0.02387559600174427, 0.035084616392850876, -0.005078884772956371, 0.003232750575989485, 0.05020195618271828, 0.0012132892152294517, 0.03108600154519081, 0.04695146903395653, 0.0034729898907244205, 0.016742585226893425, 0.00808751955628395, 0.012195773422718048, -0.006997575052082539, 0.03549737483263016, 0.037251606583595276, -0.02897060476243496, 0.032117899507284164, -0.03583274409174919, -0.029692934826016426, 0.05474231764674187, -0.008564773947000504, 0.03353676572442055, 0.012157076969742775, -0.029305972158908844, 0.024855902418494225, -0.04065687581896782, -0.01138315163552761, -0.04088905453681946, 0.01138315163552761, 0.023075873032212257, 0.020225249230861664, -0.03149875998497009, -0.006797644309699535, 0.013311515562236309, -0.009370945394039154, 0.014794872142374516, 0.021837592124938965, -0.009480585344135761, -0.009074274450540543, -0.0

In [9]:
len(embeddings[0])

1536

In [10]:
print(embeddings[0])

[-0.01413703616708517, -0.004930549301207066, -0.009022679179906845, 0.011621778830885887, 0.020238148048520088, 0.026752019301056862, 0.02387559600174427, 0.035084616392850876, -0.005078884772956371, 0.003232750575989485, 0.05020195618271828, 0.0012132892152294517, 0.03108600154519081, 0.04695146903395653, 0.0034729898907244205, 0.016742585226893425, 0.00808751955628395, 0.012195773422718048, -0.006997575052082539, 0.03549737483263016, 0.037251606583595276, -0.02897060476243496, 0.032117899507284164, -0.03583274409174919, -0.029692934826016426, 0.05474231764674187, -0.008564773947000504, 0.03353676572442055, 0.012157076969742775, -0.029305972158908844, 0.024855902418494225, -0.04065687581896782, -0.01138315163552761, -0.04088905453681946, 0.01138315163552761, 0.023075873032212257, 0.020225249230861664, -0.03149875998497009, -0.006797644309699535, 0.013311515562236309, -0.009370945394039154, 0.014794872142374516, 0.021837592124938965, -0.009480585344135761, -0.009074274450540543, -0.02

In [11]:
docs

['cats eat and sleep',
 'dogs eat and bark',
 'cars drive fast',
 'vehicles include trucks and cars']

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

sim_matrix = cosine_similarity(embeddings)
sim_matrix

array([[1.        , 0.6126304 , 0.20352151, 0.19826302],
       [0.6126304 , 1.        , 0.26195524, 0.20035223],
       [0.20352151, 0.26195524, 1.        , 0.39919367],
       [0.19826302, 0.20035223, 0.39919367, 1.        ]])

## Open Source Embedding Models on HuggingFace

`langchain-huggingface` integrates seamlessly with LangChain, providing an efficient and effective way to utilize Hugging Face models within the LangChain ecosystem.

`HuggingFaceEmbeddings`uses `sentence-transformers` embeddings. It computes the embedding locally, using your computer resources and allows you to access open or open source embedding LLMs hosted on HuggingFace.

In [14]:
from langchain_huggingface import HuggingFaceEmbeddings

# check out model details here: https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1
model_name = "mixedbread-ai/mxbai-embed-large-v1"

hf_embeddings = HuggingFaceEmbeddings(
    model_name=model_name,
)

d:\2. My WorkSpace and Notes\1. Demystify Folders\GenerativeAI-Demystified\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [15]:
embeddings = hf_embeddings.embed_documents(docs)

In [16]:
len(embeddings)

4

In [17]:
len(embeddings[0])

1024

In [18]:
docs

['cats eat and sleep',
 'dogs eat and bark',
 'cars drive fast',
 'vehicles include trucks and cars']

In [19]:
sim_matrix = cosine_similarity(embeddings)
sim_matrix

array([[1.        , 0.52516037, 0.34221859, 0.33691793],
       [0.52516037, 1.        , 0.31728608, 0.33082586],
       [0.34221859, 0.31728608, 1.        , 0.72253327],
       [0.33691793, 0.33082586, 0.72253327, 1.        ]])

## Build a small search engine!

### Load Knowledgebase documents

In [20]:
documents = [
    'Quantum mechanics describes the behavior of very small particles.',
    'Photosynthesis is the process by which green plants make food using sunlight.',
    "Shakespeare's plays are a testament to English literature.",
    'Artificial Intelligence aims to create machines that can think and learn.',
    'The pyramids of Egypt are historical monuments that have stood for thousands of years.',
    'Biology is the study of living organisms and their interactions with the environment.',
    'Music therapy can aid in the mental well-being of individuals.',
    'The Milky Way is just one of billions of galaxies in the universe.',
    'Economic theories help understand the distribution of resources in society.',
    'Yoga is an ancient practice that involves physical postures and meditation.'
]

In [21]:
len(documents)

10

### Get document embeddings

In [22]:
document_embeddings = openai_embed_model.embed_documents(documents)

### Let's try to find the most similar document for one query

In [23]:
new_text = 'What is AI?'
new_text

'What is AI?'

In [24]:
query_embedding = openai_embed_model.embed_query(new_text)

In [25]:
cosine_similarities = cosine_similarity([query_embedding], document_embeddings)
cosine_similarities

array([[ 0.10206383,  0.09261797, -0.00531899,  0.63146206,  0.02335109,
         0.09318049,  0.10767013,  0.07006562,  0.05819156,  0.06611541]])

In [26]:
import numpy as np

documents[np.argmax(cosine_similarities[0])]

'Artificial Intelligence aims to create machines that can think and learn.'

### Create Search Engine function

In [0]:
def semantic_search_engine(query, embedder_model):
  query_embedding = embedder_model.embed_query(query)
  cos_scores = cosine_similarity([query_embedding], document_embeddings)[0]
  top_result_id = np.argmax(cos_scores)
  return documents[top_result_id]

### Try out the function

In [0]:
new_sentence = 'Tell me about AI'
semantic_search_engine(new_sentence, openai_embed_model)

'Artificial Intelligence aims to create machines that can think and learn.'

In [0]:
new_sentence = 'Do you know about the pyramids?'
semantic_search_engine(new_sentence, openai_embed_model)

'The pyramids of Egypt are historical monuments that have stood for thousands of years.'

In [0]:
new_sentence = 'How do plants survive?'
semantic_search_engine(new_sentence, openai_embed_model)

'Photosynthesis is the process by which green plants make food using sunlight.'